config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "find_food", to: "pages#find_food", as: "find_food"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :users
    belongs_to :restaurants

    validates :rating, presence: true
    validates :user_id, presence: true
    validates :restaurant_id, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :ratings

    validates :name, presence: true, uniqueness: true
    validates :city, presence: true
    validates :country, presence: true
    validates :genre, presence: true

    def avg_rating
        return 0 if ratings.count == 0
        sum = 0
        ratings.each do |rating|
            sum += rating.rating
        end
        return sum.to_f / ratings.count
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :ratings
  has_many :restaurants

  validates :email, presence: true, uniqueness: true
  validates :city, presence: true

  def num_ratings
    return ratings.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to find_food_url, notice: "Successfully logged in!"
    else
      flash.now[:alert] = "Email or password is invalid. Please try again."
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    session[:user_id] = nil
    redirect_to login_url, notice: "Successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :city, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Find Me Food!</h1>
<% if !current_user%>
    <p>Welcome to Find Me Food! Please login or sign up below to store your results!</p>
    <%= link_to "Login", login_path %> |
    <%= link_to "Sign Up", signup_path%>
<% else %>
    <p>Currently logged in as <%= current_user.email %>. <%= link_to "Log Out", logout_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Findfoodapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/find_food.html.erb
<p id=”notice”><%= notice %></p>
<h1>Find Me Food!</h1>

<p>Hello,
<% if current_user.first_name == "" %>
    <%= current_user.email + "."%>
<% else %>
    <%= current_user.first_name + " " + current_user.last_name + "." %>
<% end %>|
<%= link_to "Log Out", logout_path %></p>

<% if current_user.num_ratings == 0%>
    <p>It looks like you have no ratings! Please rate restaurants to have them displayed for easy selection.</p>
<% else %>
    <h2>Previous Restaurants</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>City</th>
                <th>Genre</th>
            </tr>
        </thead>
        <tbody>
            <% current_user.rating.each do |rating| %>
                restaurant = Restaurant.find(rating.restaurant_id)
                <tr>
                    <td>restaurant.name</td>
                    <td>restaurant.city</td>
                    <td>restaurant.genre</td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= link_to 'Show User', @user %> |
<%= link_to 'All Users', users_path %>
<p></p>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% if current_user %>
  <p>Logged in as <%= current_user.email %>. <%= link_to "Log Out", logout_path %></p>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>
<%= link_to 'Home', root_path %> |
<%= link_to 'New User', new_user_path %>
<p></p>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>City</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.city %></td>
        <td><%= user.country %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure you want to delete the user: ' + user.first_name + ' ' + user.last_name + '?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>
<%= link_to "Home", root_path%>
<p></p>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Show User: <%= @user.first_name %> <%= @user.last_name%></h1>
<%= link_to 'Edit User', edit_user_path(@user) %> |
<%= link_to 'All Users', users_path %>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>